---
version: '3.7'
services:
  mirror:
    container_name: cnbc-mirror
    image: registry:2
    ports:
      - 5001:5001
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ./cnbcmirror.yml:/etc/docker/registry/config.yml
      - cnbc-mirror:/var/lib/registry
    restart: always
  registry:
    container_name: cnbc-registry
    image: registry:2
    ports:
      - 5000:5000
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ./cnbcregistry.yml:/etc/docker/registry/config.yml
      - cnbc-registry:/var/lib/registry
    restart: always
volumes:
  cnbc-mirror:
  cnbc-registry:
