#!/usr/bin/env bash

export \
  NERDCTL_VERSION=${NERDCTL_VERSION:-'1.7.7'} \
  KUBERNETES_VERSION=${KUBERNETES_VERSION:-'1.32.3'} \
  ETCD_VERSION='3.5.21' \
  CONTAINERD_VERSION='1.7.27' \
  CNI_PLUGINS_VERSION='1.6.2' \
  COREDNS_CHART_VERSION='1.39.2' \
  CILIUM_CHART_VERSION='1.17.2' \
  METRICS_SERVER_CHART_VERSION='3.12.2' \
  KONNECTIFITY_VERSION='0.32.0' \
  UBUNTU_VERSION='22.04' \
  SERVICE_CLUSTER_IP_RANGE='10.43.0.0/16' \
  SERVICE_NODE_PORT_RANGE='30000-32767' \
  CLUSTER_CIDR='10.42.0.0/16' \
  DNS_CLUSTER_IP='10.42.0.10' \
  REGISTRY_IP='192.168.1.2' \
  KUBE_PROXY_ENABLED=off \
  CLUSTER_DOMAIN=${CLUSTER_DOMAIN:-cluster.local} \
  COUNTRY="${COUNTRY:-DE}" \
  CITY="${CITY:-Bochum}" \
  STATE="${STATE:-NRW}" \
  MULTIPASS_ENABLED=${MULTIPASS_ENABLED:-off} \
  REGISTRY_ENABLED=${REGISTRY_ENABLED:-off}

if command -v ipcalc &> /dev/null ; then
  export KUBE_API_CLUSTER_IP="$(ipcalc "${SERVICE_CLUSTER_IP_RANGE}" | grep 'HostMin' | awk '{ print $2 }')"
else
  export KUBE_API_CLUSTER_IP=10.43.0.1
fi