apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
  name: policy
spec:
#  serviceSelector:
#    matchLabels:
#      pool: blue
#  nodeSelector:
#    matchExpressions:
#      - key: node-role.kubernetes.io/control-plane
#        operator: DoesNotExist
  interfaces:
  - ^ens[0-9]+
  - ^enp[0-9]+s0
  externalIPs: true
  loadBalancerIPs: true
